### ISSUE TITLE
Mod only works for the host of a MP lobby

### ISSUE THREAD

**Issue by NeverEndingCycle** [ThatWugg/muck-itemchoice#1]
I have 3 friends who installed this mod and it only lets the host pick/change the perk that spawns. Occasionally it doesn't even spawn the perk for my friends. Whenever we switch hosts that person can pick perks but no ones else. We tried re-installing, playing with only your mod and nothing worked. Mod was installed with TSMM.

**Comment by john-vu0** [comment]
I am sorry that this is happening, I will try to fix this, but I stopped working on this project some time ago. For now, the best I can recommend is downgrading to a lower version. Hopefully that the downgraded version has a working multiplayer. If it doesn't. I am sorry.

**Comment by NeverEndingCycle** [comment]
All good, while I would really appreciate an update, I can confirm that version 1.0.2 appears to work as intended so we will be using that until you can get around to updating it. Thank you so much for the quick response!

**Comment by john-vu0** [comment]
So I "updated" the plugin, basically it just removed the config, which is unfortunate because it would've been nice, but without networking and handling packets, which requires too much work and I don't have the time for that, it wouldn't work with multiplayer. Basically, what this version just does it make the ui better from 1.0.2. Now hopefully there shouldn't be any more problems (I'm aware of another problem with the powerup-choosing object not changing to its picked powerup when seen from a different client. This isn't too important).

**Comment by NeverEndingCycle** [comment]
Thank you so much for coming back to this project and updating it so quickly. Enjoy whatever you move onto next!
